//
// Created by Rainy Memory on 2021/4/13.
//

#ifndef TICKETSYSTEM_AUTOMATA_ADMINISTRATOR_H
#define TICKETSYSTEM_AUTOMATA_ADMINISTRATOR_H


class Administrator {

};


#endif //TICKETSYSTEM_AUTOMATA_ADMINISTRATOR_H
