//
// Created by Rainy Memory on 2021/4/14.
//

#ifndef TICKETSYSTEM_AUTOMATA_ORDERMANAGER_H
#define TICKETSYSTEM_AUTOMATA_ORDERMANAGER_H


class OrderManager {

};


#endif //TICKETSYSTEM_AUTOMATA_ORDERMANAGER_H
