//
// Created by Rainy Memory on 2021/4/14.
//

#ifndef TICKETSYSTEM_AUTOMATA_TRAINMANAGER_H
#define TICKETSYSTEM_AUTOMATA_TRAINMANAGER_H


class TrainManager {

};


#endif //TICKETSYSTEM_AUTOMATA_TRAINMANAGER_H
